### ISSUE TITLE
Loading saved projects (load wavs folder with saved txt document)

### ISSUE THREAD

**Issue by awesomeface349** [underscoren/transcribetool#2]
So, let's say you already done with the voice model, but you've just added more wavs to it. 

So what if load a saved text document with saved wavs to it, so that it could be load just like saved projects.

**Comment by underscoren** [comment]
An "import" feature for existing datasets in the tacotron format is definitely something I can work on.

Unless you're talking about loading a dataset you were previously working on using TranscribeTool, in which case that's already a thing, when the wav files are loaded, it checks for existing txt files and fills in the textboxes automatically.
